services:
  - type: web
    name: productos-api
    runtime: image
    image:
      url: docker.io/angxi/productos-api:latest
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: productos-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: productos-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: productos-db
          property: database
      - key: DATABASE_USERNAME
        fromDatabase:
          name: productos-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: productos-db
          property: password
      - key: PORT
        value: "8080"

databases:
  - name: productos-db
    databaseName: productosdb
    plan: free