spring:
  application:
    name: productos-api

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:productosdb}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    pool:
      initial-size: 2
      max-size: 5
      max-idle-time: 30m

  sql:
    init:
      mode: always

server:
  port: ${PORT:8080}

logging:
  level:
    com.api.productos: DEBUG
    org.springframework.r2dbc: DEBUG